### ISSUE TITLE
1.0 Release Tracker

### ISSUE THREAD

**Issue by Relintai** [Relintai/entity_spell_system#1]
This Issue tracks the things that need to be done for the first release.

- [ ] Make dependencies to my other modules optional.
- [ ] Documentation (Sphinx)
- [ ] Class docs (XML) - At least the things that are not self explanatory.
- [ ] Sound Support
- [ ] WorldSpell's logic
- [ ] Implement all generic spell effects
- [ ] Implement all generic aura effects
- [ ] Fix AI
- [ ] Finish the setup for pet support (I already have the design for it, just need to code it.)
- [ ] Port everything that belongs here from Broken Seals

**Comment by Relintai** [comment]
Not as clear cut.
